content = [['EleG', 'EleM', 'DilG', 'DilM', 'PolG', 'ThulG', 'ThulM', 'ProG', 'RuthG', 'RuthM', 'CobG', 'CobM'], ['PolM', 'ProM'], [], []]
#1 [['EleG', 'EleM', 'DilG', 'DilM', 'ThulG', 'ThulM',  'RuthG', 'RuthM', 'CobG', 'CobM'], ['EEE', 'PolG', 'PolM', 'ProG', 'ProM'], [], []]
#2 [['EleG', 'EleM', 'DilG', 'DilM', 'ThulG', 'ThulM',  'RuthG', 'RuthM', 'CobG', 'CobM'], ['PolG', 'PolM'], ['EEE', 'ProG', 'ProM'], []]
#3 [['EleG', 'EleM', 'DilG', 'DilM', 'ThulG', 'ThulM',  'RuthG', 'RuthM', 'CobG', 'CobM'], ['PolG', 'PolM'], [], ['EEE', 'ProG', 'ProM']]
#4 [['EleG', 'EleM', 'DilG', 'DilM', 'ThulG', 'ThulM',  'RuthG', 'RuthM', 'CobG', 'CobM'], ['PolG', 'PolM'], ['EEE', 'ProG'], ['ProM']]
#5 [['EleG', 'EleM', 'DilG', 'DilM', 'ThulG', 'ThulM',  'RuthG', 'RuthM', 'CobG', 'CobM'], ['EEE', 'PolG', 'PolM', 'ProG'], [], ['ProM']]
#6 [['EleG', 'EleM', 'DilG', 'DilM', 'ThulG', 'ThulM',  'RuthG', 'RuthM', 'CobG', 'CobM'], ['ProG'], ['EEE', 'PolG', 'PolM'], ['ProM']]
#7 [['EleG', 'EleM', 'DilG', 'DilM', 'ThulG', 'ThulM',  'RuthG', 'RuthM', 'CobG', 'CobM'], ['ProG'], [], ['EEE', 'PolG', 'PolM', 'ProM']]
#11 [['EleG', 'EleM', 'DilG', 'DilM', 'ThulG', 'ThulM',  'RuthG', 'RuthM', 'CobG', 'CobM'], [], [], ['EEE', 'PolG', 'PolM', 'ProG', 'ProM']]
#14 [['EleG', 'EleM', 'DilG', 'DilM', 'ThulG', 'ThulM',  'RuthG', 'RuthM', 'CobG', 'CobM', 'PolG', 'EEE'], [], [], ['PolM', 'ProG', 'ProM']]
#17 [['EleG', 'EleM', 'DilG', 'DilM', 'ThulG', 'ThulM',  'RuthG', 'RuthM', 'PolG'], [], [], ['EEE', 'CobG', 'CobM', 'PolM', 'ProG', 'ProM']]
#20 [['EleG', 'EleM', 'DilG', 'DilM', 'ThulG', 'ThulM',  'RuthG', 'RuthM', 'PolG', 'CobG', 'EEE'], [], [], ['CobM', 'PolM', 'ProG', 'ProM']]
#23 [['EleG', 'EleM', 'DilG', 'DilM', 'ThulG', 'ThulM', 'PolG', 'CobG'], [], [], ['EEE', 'RuthG', 'RuthM', 'CobM', 'PolM', 'ProG', 'ProM']]
#26 [['EleG', 'EleM', 'DilG', 'DilM', 'ThulG', 'ThulM', 'PolG', 'CobG', 'RuthG', 'EEE'], [], [], ['RuthM', 'CobM', 'PolM', 'ProG', 'ProM']]
#32 [['EleG', 'EleM', 'DilG', 'DilM', 'ThulG', 'PolG', 'CobG', 'RuthG', 'EEE'], [], [], ['ThulM', 'RuthM', 'CobM', 'PolM', 'ProG', 'ProM']]
#38 [['EleG', 'DilG', 'DilM', 'ThulG', 'PolG', 'CobG', 'RuthG', 'EEE'], [], [], ['EleM', 'ThulM', 'RuthM', 'CobM', 'PolM', 'ProG', 'ProM']]
#44 [['EleG', 'DilG', 'ThulG', 'PolG', 'CobG', 'RuthG', 'EEE'], [], [], ['DilM', 'EleM', 'ThulM', 'RuthM', 'CobM', 'PolM', 'ProG', 'ProM']]
#50 [['DilG', 'ThulG', 'PolG', 'CobG', 'RuthG', 'EEE'], [], [], ['EleG', 'DilM', 'EleM', 'ThulM', 'RuthM', 'CobM', 'PolM', 'ProG', 'ProM']]
#56 [['ThulG', 'PolG', 'CobG', 'RuthG', 'EEE'], [], [], ['DilG', 'EleG', 'DilM', 'EleM', 'ThulM', 'RuthM', 'CobM', 'PolM', 'ProG', 'ProM']]
#62 [['PolG', 'CobG', 'RuthG', 'EEE'], [], [], ['ThulG', 'DilG', 'EleG', 'DilM', 'EleM', 'ThulM', 'RuthM', 'CobM', 'PolM', 'ProG', 'ProM']]
#68 [['CobG', 'RuthG', 'EEE'], [], [], ['PolG', 'ThulG', 'DilG', 'EleG', 'DilM', 'EleM', 'ThulM', 'RuthM', 'CobM', 'PolM', 'ProG', 'ProM']]
#74 [[], [], [], ['EEE', 'CobG', 'RuthG', 'PolG', 'ThulG', 'DilG', 'EleG', 'DilM', 'EleM', 'ThulM', 'RuthM', 'CobM', 'PolM', 'ProG', 'ProM']]
